server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: piranavan
      password: iampiranavan
    realmImportFile: realm-export.json
